<?php
$imageModels = array(
   'honda' => array (
     '2012' => array (
       'silverwing' => array(
         'file' => '2012_Honda_SilverWing_ABS.jpg',
         'name' => 'SilverWing',
         'alt' => 'Honda SilverWing ABS',
         'body' => 'Touring Scooter',
         'msrp' => '',
       ),
     ),
     '2013' => array (
       'cbr' => array(
         'file' => '2013_Honda_CBR_600RRABS.jpg',
         'name' => 'CBR',
         'alt' => 'Honda CBR 600RRABS',
         'body' => 'Sport',
         'msrp' => '',
       ),
       'cb' => array(
         'file' => '2013_Honda_CB_500X.jpg',
         'name' => 'CB',
         'alt' => 'Honda CB 500X',
         'body' => 'Standard',
         'msrp' => '11780',
       ),
       'crf' => array(
         'file' => '2013_Honda_CRF_80F.jpg',
         'name' => 'CRF',
         'alt' => 'Honda CRF 80F',
         'body' => 'Off-Road',
         'msrp' => '',
       ),
       'fury' => array(
         'file' => '2013_Honda_Fury_Base.jpg',
         'name' => 'Fury',
         'alt' => 'Honda Fury Base',
         'body' => 'Chopper',
         'msrp' => '13390',
       ),
       'goldwing' => array(
         'file' => '2013_Honda_GoldWing_F6BDeluxe.jpg',
         'name' => 'GoldWing',
         'alt' => 'Honda GoldWing F6BDeluxe',
         'body' => 'Touring',
         'msrp' => '26880',
       ),
       'interstate' => array(
         'file' => '2013_Honda_Interstate.jpg',
         'name' => 'Interstate',
         'alt' => 'Honda Interstate ',
         'body' => 'Cruiser',
         'msrp' => '13240',
       ),
       'metropolitan' => array(
         'file' => '2013_Honda_Metropolitan_Base.jpg',
         'name' => 'Metropolitan',
         'alt' => 'Honda Metropolitan Base',
         'body' => 'Scooter',
         'msrp' => '1999',
       ),
       'nc700x' => array(
         'file' => '2013_Honda_NC700X_DCTABS.jpg',
         'name' => 'NC700X',
         'alt' => 'Honda NC700X DCTABS',
         'body' => 'Standard',
         'msrp' => '8499',
       ),
       'pcx' => array(
         'file' => '2013_Honda_PCX_150.jpg',
         'name' => 'PCX',
         'alt' => 'Honda PCX 150',
         'body' => 'Scooter',
         'msrp' => '',
       ),
       'rebel' => array(
         'file' => '2013_Honda_Rebel_Base.jpg',
         'name' => 'Rebel',
         'alt' => 'Honda Rebel Base',
         'body' => 'Cruiser',
         'msrp' => '',
       ),
       'ruckus' => array(
         'file' => '2013_Honda_Ruckus_Base.jpg',
         'name' => 'Ruckus',
         'alt' => 'Honda Ruckus Base',
         'body' => 'Scooter',
         'msrp' => '2649',
       ),
       'sabre' => array(
         'file' => '2013_Honda_Sabre.jpg',
         'name' => 'Sabre',
         'alt' => 'Honda Sabre ',
         'body' => 'Cruiser',
         'msrp' => '12250',
       ),
       'shadow' => array(
         'file' => '2013_Honda_Shadow_Spirit750C2ABS.jpg',
         'name' => 'Shadow',
         'alt' => 'Honda Shadow Spirit750C2ABS',
         'body' => 'Cruiser',
         'msrp' => '',
       ),
       'stateline' => array(
         'file' => '2013_Honda_Stateline.jpg',
         'name' => 'Stateline',
         'alt' => 'Honda Stateline ',
         'body' => 'Cruiser',
         'msrp' => '12150',
       ),
       'vfr' => array(
         'file' => '2013_Honda_VFR_1200F.jpg',
         'name' => 'VFR',
         'alt' => 'Honda VFR 1200F',
         'body' => 'Sport',
         'msrp' => '17499',
       ),
       'xr' => array(
         'file' => '2013_Honda_XR_650L.jpg',
         'name' => 'XR',
         'alt' => 'Honda XR 650L',
         'body' => 'On-Off Road',
         'msrp' => '',
       ),
     ),
     '2014' => array (
       'cbr' => array(
         'file' => '2014_Honda_CBR_600RRABS.jpg',
         'name' => 'CBR',
         'alt' => 'Honda CBR 600RRABS',
         'body' => 'Sport',
         'msrp' => '',
       ),
       'cb' => array(
         'file' => '2014_Honda_CB_500X.jpg',
         'name' => 'CB',
         'alt' => 'Honda CB 500X',
         'body' => 'Standard',
         'msrp' => '11780',
       ),
       'crf' => array(
         'file' => '2014_Honda_CRF_50F.jpg',
         'name' => 'CRF',
         'alt' => 'Honda CRF 50F',
         'body' => 'Off-Road',
         'msrp' => '',
       ),
       'ctx' => array(
         'file' => '2014_Honda_CTX_700NDCTABS.jpg',
         'name' => 'CTX',
         'alt' => 'Honda CTX 700NDCTABS',
         'body' => 'Sport-Touring',
         'msrp' => '8799',
       ),
       'forza' => array(
         'file' => '2014_Honda_Forza_ABS.jpg',
         'name' => 'Forza',
         'alt' => 'Honda Forza ABS',
         'body' => 'Scooter',
         'msrp' => '5599',
       ),
       'fury' => array(
         'file' => '2014_Honda_Fury_Base.jpg',
         'name' => 'Fury',
         'alt' => 'Honda Fury Base',
         'body' => 'Chopper',
         'msrp' => '13390',
       ),
       'goldwing' => array(
         'file' => '2014_Honda_GoldWing_F6BDeluxe.jpg',
         'name' => 'GoldWing',
         'alt' => 'Honda GoldWing F6BDeluxe',
         'body' => 'Touring',
         'msrp' => '26880',
       ),
       'grom' => array(
         'file' => '2014_Honda_Grom_Base.jpg',
         'name' => 'Grom',
         'alt' => 'Honda Grom Base',
         'body' => 'Standard',
         'msrp' => '2999',
       ),
       'interceptor' => array(
         'file' => '2014_Honda_Interceptor_Base.jpg',
         'name' => 'Interceptor',
         'alt' => 'Honda Interceptor Base',
         'body' => 'Sport',
         'msrp' => '13499',
       ),
       'interstate' => array(
         'file' => '2014_Honda_Interstate.jpg',
         'name' => 'Interstate',
         'alt' => 'Honda Interstate ',
         'body' => 'Cruiser',
         'msrp' => '13240',
       ),
       'metropolitan' => array(
         'file' => '2014_Honda_Metropolitan_Base.jpg',
         'name' => 'Metropolitan',
         'alt' => 'Honda Metropolitan Base',
         'body' => 'Scooter',
         'msrp' => '1999',
       ),
       'montesa' => array(
         'file' => '2014_Honda_Montesa_Cota4RTRepsolEdition.jpg',
         'name' => 'Montesa',
         'alt' => 'Honda Montesa Cota4RTRepsolEdition',
         'body' => 'Off-Road',
         'msrp' => '8999',
       ),
       'rebel' => array(
         'file' => '2014_Honda_Rebel_Base.jpg',
         'name' => 'Rebel',
         'alt' => 'Honda Rebel Base',
         'body' => 'Cruiser',
         'msrp' => '',
       ),
       'ruckus' => array(
         'file' => '2014_Honda_Ruckus_Base.jpg',
         'name' => 'Ruckus',
         'alt' => 'Honda Ruckus Base',
         'body' => 'Scooter',
         'msrp' => '2649',
       ),
       'sabre' => array(
         'file' => '2014_Honda_Sabre.jpg',
         'name' => 'Sabre',
         'alt' => 'Honda Sabre ',
         'body' => 'Cruiser',
         'msrp' => '12250',
       ),
       'shadow' => array(
         'file' => '2014_Honda_Shadow_Spirit750ABS.jpg',
         'name' => 'Shadow',
         'alt' => 'Honda Shadow Spirit750ABS',
         'body' => 'Cruiser',
         'msrp' => '',
       ),
       'stateline' => array(
         'file' => '2014_Honda_Stateline.jpg',
         'name' => 'Stateline',
         'alt' => 'Honda Stateline ',
         'body' => 'Cruiser',
         'msrp' => '12150',
       ),
       'valkyrie' => array(
         'file' => '2014_Honda_Valkyrie.jpg',
         'name' => 'Valkyrie',
         'alt' => 'Honda Valkyrie ',
         'body' => 'Cruiser',
         'msrp' => '',
       ),
       'xr' => array(
         'file' => '2014_Honda_XR_650L.jpg',
         'name' => 'XR',
         'alt' => 'Honda XR 650L',
         'body' => 'On-Off Road',
         'msrp' => '',
       ),
     ),
 ),
);
?>